apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: root
    jsonData:
      database: ecommerce_analytics
      sslmode: disable
      postgresVersion: 1300
    isDefault: true
